version: '3.6'

services:

  db:
    container_name: heycar-test-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=heycar
      - POSTGRES_USER=postgres
    volumes:
      - dev-heycar-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    container_name: heycar-test-app
    build:
      context: ../..
      dockerfile: .docker/Dockerfile
    image: heycar-test
    command: sh -c "/app/wait-for-it.sh postgres:5432 && alembic upgrade head && python server.py"
    depends_on:
      - db
    volumes:
      - ../..:/app
    ports:
      - 8080:5000
    environment:
      - DB_HOST=postgres
      - DB_DBNAME=heycar
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - LOG_LEVEL=DEBUG
      - ENV=dev
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - S3_BUCKET=heycar-davidfelce-test
    links:
      - db:postgres

volumes:
  dev-heycar-pgdata:
    driver: local

