"""image_url

Revision ID: ef2b2673042d
Revises: db4a696fc11b
Create Date: 2020-05-05 10:53:40.921385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2b2673042d'
down_revision = 'db4a696fc11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'image_url')
    # ### end Alembic commands ###
